# Generated by Django 4.2.1 on 2023-09-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='topic',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notice',
            name='topic',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
