# Generated by Django 4.2.1 on 2023-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='topic',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
