# Generated by Django 4.2.1 on 2023-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='specialization',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.CharField(blank=True, default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='field_of_interest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='Null', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
