# Generated by Django 4.2.1 on 2023-06-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_student_staff_alumni'),
        ('accounts', '0003_alter_users_options'),
    ]

    operations = [
    ]
