# Generated by Django 4.2.1 on 2023-07-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_semester_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Batch',
            field=models.CharField(default='2019-2022', max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Degree',
            field=models.CharField(default='B.Tech (CSE)', max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='collage_id',
            field=models.CharField(default='As per colage records', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='current_company',
            field=models.CharField(default='If any else None', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(default='022'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Assistant Professor', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_interest',
            field=models.CharField(blank=True, default='web dev / devops', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='As per colage records', max_length=100),
        ),
    ]
