# Generated by Django 4.2.1 on 2023-07-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alumni_batch_alumni_degree_alumni_collage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'faculty Member'), ('alumni', 'Alumni')], max_length=10),
        ),
    ]
